### ISSUE TITLE
React 17 中移除了 “event pooling（事件池）“

### ISSUE THREAD

**Issue by xiaolu-lujunji** [muyiwoniu/Front-End-Web-Development-Interview#1]
## 问题描述
在 1. React 的事件和普通的 HTML 事件有什么不同？这个问题中，
原文出现了如下一个观点：https://github.com/muyiwoniu/Front-End-Web-Development-Interview/blob/main/questions/React.md?plain=1#L12 ，我认为这个观点需要备注上React的具体版本。

## 我的观点
在 React 17 相关改动这篇文章中 https://zh-hans.reactjs.org/blog/2020/08/10/react-v17-rc.html#no-event-pooling ，明确表示了React 17 中移除了 “event pooling（事件池）“。

**Comment by muyiwoniu** [comment]
感谢您的指正

**Comment by muyiwoniu** [comment]
g
